spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: kid0510
    url: jdbc:mysql:///vhr?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
server:
  port: 9080
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
